### ISSUE TITLE
flower classifier

### ISSUE THREAD

**Issue by bgomiss** [Goku132/Flower-Classifier-ML#1]
could you add the converted model .mlmodel into your repository please?

**Comment by Goku132** [comment]
Sorry I can't find it since I moved devices. I think it was too large to upload. 
This was when I was learning iOS dev from the udemy course: https://www.udemy.com/course/ios-13-app-development-bootcamp/
If you are interested in the course it may have the topic still there or if you look trough different repos.

**Comment by bgomiss** [comment]
Thank you very much for your response. I'm already getting that course from
Angela Yu. I'm towards the end of the course. Did you finish it and it
helped you learn Swift? Now do you work as iOS developer?

**Comment by Goku132** [comment]
Finished it help me learn alot from swift and all other parts. Currently I don't working with iOS. But did afterwards, helped alot to be a strong junior iOS dev.
